//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_SQLVol2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public System.Guid UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string KarmaPoints { get; set; }
        public string FacebookLink { get; set; }
        public string Age { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
    }
}
